[theme]
primaryColor = "#1DB954"          # Spotify Green
backgroundColor = "#121212"      # Spotify Dark Background
secondaryBackgroundColor = "#282828" # Darker Grey Sidebar/Cards
textColor = "#FFFFFF"            # White text
font = "sans serif"